# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipingDuplex < Formula
  desc "Duplex communication over Piping Server"
  homepage "https://github.com/nwtgck/go-piping-duplex"
  version "0.3.0-release-trigger2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-duplex/releases/download/v0.3.0-release-trigger2/piping-duplex-0.3.0-release-trigger2-darwin-amd64.tar.gz"
    sha256 "4eadaebff1e941f53f2919029153f0c98492b92c5a49e326144f4c5cfe6c7342"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nwtgck/go-piping-duplex/releases/download/v0.3.0-release-trigger2/piping-duplex-0.3.0-release-trigger2-darwin-arm64.tar.gz"
    sha256 "4e7509d9ef6f8970b94c5d539065591a291d895f1495bd86a51b12838b99a5af"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-duplex/releases/download/v0.3.0-release-trigger2/piping-duplex-0.3.0-release-trigger2-linux-amd64.tar.gz"
    sha256 "150b96dddec229f56dd4e778c6e10e4870b20521d1db56397c98bad1eb0754e7"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-duplex/releases/download/v0.3.0-release-trigger2/piping-duplex-0.3.0-release-trigger2-linux-armv6.tar.gz"
    sha256 "c2218222cb13b51081fc9afd1708238bdc5371c46d46ae960c48afd8052f4489"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-duplex/releases/download/v0.3.0-release-trigger2/piping-duplex-0.3.0-release-trigger2-linux-arm64.tar.gz"
    sha256 "0c295d1344888424b9e51fbdb31e05e89ede4de91c7e7582f17f1d47c0f61806"
  end

  def install
    bin.install "piping-duplex"
  end
end
